import os

EMBEDDING_MODEL = "all-MiniLM-L6-v2"
MAX_RESULTS = 5
MIN_SCORE_THRESHOLD = 0.2
SEARCH_LIMIT = MAX_RESULTS
MIN_SEARCH_SCORE = MIN_SCORE_THRESHOLD
LLM_MODEL = "gemini-2.5-flash"
GOOGLE_API_KEY = os.getenv("GOOGLE_API_KEY")
